searching_sportsmen/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('sport_catalog/',include('sport_catalog.urls')),
    path('', RedirectView.as_view(url='/sport_catalog/', permanent=True)),

    path('sport_catalog/', RedirectView.as_view(url='/sport_catalog/', permanent=True)),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

sport_catalog/urls.py
from django.urls import path, re_path
from django.urls import include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('test/',views.test, name="test" ),
    path('events/', views.AllEventsListView.as_view(), name="all_events" ),
    path('sportsmen/', views.AllSportUsers.as_view(), name="all_sportsmen" ),
    path('managers/', views.AllManagerUsers.as_view(), name="all_managers" ),
    path('reviews/', views.AllReviewsListView.as_view(), name="all_reviews" ),

    re_path(r'^myEvents/$', views.EventsByUserListView.as_view(), name='my-events'),
    re_path(r'^myReviews/$', views.ReviewsByUserListView.as_view(), name='my-reviews'),
    re_path(r'^myComplaints/$', views.ComplaintsByUserListView.as_view(), name='my-complaints'),
    re_path(r'^event/(?P<pk>[0-9a-f-]+)$', views.EventDetailedView.as_view(), name='event-detail'),
    re_path(r'^review/(?P<pk>[0-9a-f-]+)$', views.ReviewDetailedView.as_view(), name='review-detail'),
    re_path(r'^complaint/(?P<pk>[0-9a-f-]+)$', views.ComplaintsDetailedView.as_view(), name='complaint-detail'),
    
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^edit/$', views.edit, name='edit'),

    re_path(r'^sportsman/(?P<pk>[0-9a-f-]+)$', views.SportuserDetailedView.as_view(), name='sportuser-detail'),

]

urlpatterns += [
    re_path(r'^event/create/$', views.EventCreate.as_view(), name='event_create'),
   # re_path(r'^event/(?P<pk>[0-9a-f-]+)/update/$', views.AuthorUpdate.as_view(), name='event_update'),
    #re_path(r'^event/(?P<pk>[0-9a-f-]+)/delete/$', views.AuthorDelete.as_view(), name='event_delete'),
]

urlpatterns += [
    re_path(r'^review/create/$', views.ReviewCreate.as_view(), name='review_create'),
   # re_path(r'^review/(?P<pk>[0-9a-f-]+)/update/$', views.ReviewUpdate.as_view(), name='review_update'),
    #re_path(r'^review/(?P<pk>[0-9a-f-]+)/delete/$', views.ReviewDelete.as_view(), name='review_delete'),
]

sport_catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from django.conf import settings
 
from datetime import date

class SportUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, help_text = "enter first name" )
    last_name = models.CharField(max_length=100, help_text = "enter last name" )
    isSportsMen = models.BooleanField()
    isManager = models.BooleanField()

    def get_absolute_url(self):
        """
        Returns the url to access a sportuser
        """
        return reverse('sportuser-detail', args=[str(self.id)])
    
    def __str__(self):
        #"""
        #String for representing the Model object (in Admin site etc.)
        #"""
        return self.user.get_username()



class SportType(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    type_name = models.CharField(max_length=200, help_text="Enter a sport type")

    def __str__(self):
        #"""
        #String for representing the Model object (in Admin site etc.)
        #"""
        return self.type_name


class ProcessingStatus(models.Model):
    description = models.CharField(max_length=50, help_text="Enter status of process")
    def __str__(self):
        return self.description


class Event(models.Model):
    """
    Model representing a specific copy of a book (i.e. that can be borrowed from the library).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID of event")
    sport_type =  models.ForeignKey(SportType, on_delete=models.SET_NULL, null=True, blank=True)
    manager =  models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date= models.DateField(null=True, blank=True)
    time= models.TimeField(null=True, blank=True)
    address = models.CharField(max_length=50, help_text="Enter address")
    comment = models.TextField(max_length=500, help_text="Enter comment")
    isClosed = models.BooleanField()
    def __str__(self):
        return '%s (%s)' % (self.id,self.manager)
    
    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('event-detail', args=[str(self.id)])


#class ReceiverOfReview(models.Model):
 #   reciever =  models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
  #  def __str__(self):
   #     return '%s' % (self.reciever)



#class SenderOfReview(models.Model):
 #   sender =  models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
  #  def __str__(self):
   #     return '%s' % (self.sender)

class Review(models.Model):
    reciever =  models.ForeignKey(SportUser,on_delete=models.CASCADE, related_name="rcv")
    sender =  models.ForeignKey(SportUser,on_delete=models.CASCADE, related_name="snd")

    #sender =  models.ForeignKey(SenderOfReview, on_delete=models.SET_NULL, null=True, blank=True)
    mark = models.IntegerField()
    comment = models.TextField(max_length=500, help_text="Enter review comment")
    reply = models.TextField(max_length=500, help_text="Enter review comment`s reply")
    isActive = models.BooleanField()
    event =  models.ForeignKey(Event, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return "review on  %s by %s" % (self.event, self.reciever)
    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('review-detail', args=[str(self.id)])

class Complaint(models.Model):
    moderator =  models.ForeignKey(SportUser, on_delete=models.SET_NULL, null=True, blank=True)
    review =  models.ForeignKey(Review, on_delete=models.SET_NULL, null=True, blank=True)
    status =  models.ForeignKey(ProcessingStatus, on_delete=models.SET_NULL, null=True, blank=True)
    comment = models.TextField(max_length=500, help_text="Enter complaint comment")
    def __str__(self):
        return "complain on %s" % (self.review)

    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('complaint-detail', args=[str(self.id)])

class Application(models.Model):
    event =  models.ForeignKey(Event, on_delete=models.SET_NULL, null=True, blank=True)
    spotsman =  models.ForeignKey(SportUser, on_delete=models.SET_NULL, null=True, blank=True)
    status =  models.ForeignKey(ProcessingStatus, on_delete=models.SET_NULL, null=True, blank=True)
    comment = models.TextField(max_length=500, help_text="Enter application comment")
    def __str__(self):
        return "application on %s by %s" % (self.event, self.spotsman)

class UsersSportTypes(models.Model):
    user = models.ForeignKey(SportUser, on_delete=models.SET_NULL, null=True, blank=True)
    sport_type = models.ManyToManyField(SportType, help_text="Select sport types")
    def __str__(self):
        return "%s of %s" % (self.sport_type, self.user)

sport_catalog/forms.py
from django.contrib.auth.models import User
from .models import SportUser
from django import forms

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']
    

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')
    
class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = SportUser
        fields = ('first_name', 'last_name', 'isManager', 'isSportsMen')

sport_catalog/views.py
from django.shortcuts import render
from .models import SportUser, SportType,  ProcessingStatus, Event, Review, Complaint,Application, UsersSportTypes

from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin

from django.contrib.auth.decorators import login_required


from .forms import  UserRegistrationForm, ProfileEditForm, UserEditForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView



def index(request):

# Create your views here.
    return render(request, 'index.html')

class EventDetailedView(generic.DetailView):
    model = Event

class SportuserDetailedView(generic.DetailView):
    model = SportUser

class ReviewDetailedView(generic.DetailView):
    model = Review

class ComplaintsDetailedView(generic.DetailView):
    model = Complaint


class AllEventsListView(generic.ListView):
    model = Event

class AllReviewsListView(generic.ListView):
    model = Review
class AllSportUsers(generic.ListView):
    model = SportUser
    template_name ='sport_catalog/sportsmen_list.html' 
    def get_queryset(self):
        return SportUser.objects.filter(isSportsMen=True)
    
class AllManagerUsers(generic.ListView):
    model = SportUser
    template_name ='sport_catalog/manager_list.html' 
    def get_queryset(self):
        return SportUser.objects.filter(isManager=True)

class EventsByUserListView(LoginRequiredMixin, generic.ListView):
    """
    Generic class-based view listing events to current user.
    """
    model = Event
    template_name ='sport_catalog/event_list_by_user.html'
    paginate_by = 10

    def get_queryset(self):
        return Event.objects.filter(manager=self.request.user).order_by('date')
    
class ComplaintsByUserListView(LoginRequiredMixin, generic.ListView):
    """
    Generic class-based view listing events to current user.
    """
    model = Complaint
    template_name ='sport_catalog/complaint_list_by_user.html'
    paginate_by = 10

   
    def get_queryset(self):
        print("+++++++++++++++++++++++++++++++++++++")

        su = SportUser.objects.filter(user= self.request.user)[0]

        print(su)
        print("+++++++++++++++++++++++++++++++++++++")


        hu = Review.objects.filter(sender = su)
        print(hu)

        print("+++++++++++++++++++++++++++++++++++++")
        #print(Complaint.objects.filter(review in hu))
        return Complaint.objects.filter(review = hu[0])
    
class ReviewsByUserListView(LoginRequiredMixin, generic.ListView):
    """
    Generic class-based view listing events to current user.
    """
    model = Review
    template_name ='sport_catalog/review_list_by_user.html'
    paginate_by = 10

    def get_queryset(self):
        su = SportUser.objects.filter(user= self.request.user)
        return Review.objects.filter(sender= su[0])

def test(request):
    #projects = Project.objects.all()
  
    context = {}
    return render(request, 'index.html', context)
    



def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])


            # Save the User object
            new_user.save()
            profile = SportUser.objects.create(user=new_user)
            return render(request, 'registration/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'user_form': user_form})

@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.SportUser, data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.sportuser)
        return render(request,
                      'registration/edit.html',
                      {'user_form': user_form,
                       'profile_form': profile_form})
    

class EventCreate(CreateView):
    model = Event
    fields = '__all__'
    #initial={'date_of_death':'12/10/2016',}

class EventUpdate(UpdateView):
    model = Event
    fields = '__all__'

class EventDelete(DeleteView):
    model = Event
    #success_url = reverse_lazy('authors')


class ReviewCreate(CreateView):
    model = Review
    fields = '__all__'
    #initial={'date_of_death':'12/10/2016',}

class ReviewUpdate(UpdateView):
    model = Review
    fields = '__all__'

class ReviewDelete(DeleteView):
    model = Review
    #success_url = reverse_lazy('authors')

sport_catalog/templates/sport_catalog/complaint_detail.html
{% extends "base_generic.html" %}
{% block content %}
  
  <h1>: {{complaint}}</h1>

  <p><strong>Review:</strong> <a href="{% url 'review-detail' complaint.review.pk %}">{{ complaint.review }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Status:</strong> {{ complaint.status }}</p>
  <p><strong>Moderator:</strong> {{ complaint.moderator }}</p>


{% endblock %}

sport_catalog/templates/sport_catalog/complaint_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <input type="submit" value="Submit" />
  </form>
{% endblock %}

sport_catalog/templates/sport_catalog/complaint_list_by_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>My review</h1>

    {% if complaint_list %}
    <ul>
      {% for complaint in complaint_list %}
      <li>
        <a href="{% url 'complaint-detail' complaint.pk %}">{{complaint}}</a> ({{ complaint.comment }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no complaints of {{ user.get_username }}</p>
    {% endif %}
{% endblock %}

sport_catalog/templates/sport_catalog/event_detail.html
{% extends "base_generic.html" %}
{% block content %}
  
  <h1>: {{ event.sport_type }}</h1>

  <p><strong>Manager:</strong> <a href="">{{ event.manager }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Date:</strong> {{ event.date }}</p>
  <p><strong>Time:</strong> {{ event.time }}</p>
  <p><strong>Addrress:</strong> {{ event.address }}</p>
  <p><strong>Comment:</strong> {{ event.comment }}</p>

{% endblock %}

sport_catalog/templates/sport_catalog/event_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <input type="submit" value="Submit" />
  </form>
{% endblock %}

sport_catalog/templates/sport_catalog/event_list.html
{% extends "base_generic.html" %}
{% block title %}


<title> Events list</title>

{% endblock %}
{% block content %}
    <h1>Events List</h1>

    {% if event_list %}
    <ul>

      {% for event in event_list %}
      <li>
        <a href="{{ event.get_absolute_url }}">{{ event.id }}</a> {{ event.sport_type }} ({{event.manager}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no events</p>
    {% endif %}
{% endblock %}

sport_catalog/templates/sport_catalog/event_list_by_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>My events</h1>

    {% if event_list %}
    <ul>
      {% for event in event_list %}
      <li >
        <a href="{% url 'event-detail' event.pk %}">{{event.sport_type}}</a> ({{ event.date }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no events managed by {{ user.get_username }}</p>
    {% endif %}

    <li><a href="{% url 'event_create'%}">Create Event</a></li>

{% endblock %}

sport_catalog/templates/sport_catalog/manager_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1> Manager`s list</h1> 

    {% if sportuser_list %}
    <ul>

      {% for sportsman in sportuser_list %}
      <li>
        <a href="{{ sportsman.get_absolute_url }}">{{ sportsman.first_name }} {{ sportsman.last_name }}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no sportsmen.</p>
    {% endif %}
{% endblock %}

sport_catalog/templates/sport_catalog/review_detail.html
{% extends "base_generic.html" %}
{% block content %}
  
  <h1>Event: {{ review.event.id }} {{ review.event.sport_type }}</h1>

  <p><strong>Receiver:</strong> <a href="{{ review.receiver.get_absolute_url }}">{{ review.receiver.first_name }} {{ review.receiver.last_name }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Sender:</strong> <a href="{{ review.sender.get_absolute_url }}">{{ review.sender.first_name }} {{ review.sender.last_name }}</a></p> <!-- author detail link not yet defined -->

  <p><strong>Mark:</strong> {{ review.mark }}</p>
  <p><strong>Comment:</strong> {{ review.comment }}</p>
  <p><strong>Reply:</strong> {{ review.reply }}</p>




{% endblock %}

sport_catalog/templates/sport_catalog/review_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <input type="submit" value="Submit" />
  </form>
{% endblock %}

sport_catalog/templates/sport_catalog/review_list.html
{% extends "base_generic.html" %}
{% block title %}


<title> Reviews list</title>

{% endblock %}
{% block content %}
    <h1>Reviews List</h1>

    {% if review_list %}
    <ul>

      {% for event in review_list %}
      <li>
       <p> ID: <a href="{{ event.get_absolute_url }}"> {{ event.id }}</a> </p>
        <p>Mark: {{ event.mark }} </p>
        <p> Comment: {{ event.comment }} </p>

      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no events</p>
    {% endif %}
{% endblock %}

sport_catalog/templates/sport_catalog/review_list_by_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>My review</h1>

    {% if review_list %}
    <ul>
      {% for review in review_list %}
      <li>
        <a href="{% url 'review-detail' review.pk %}">{{review.id}}</a> ({{ review.comment }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no review for {{ user.get_username }}</p>
    {% endif %}
    <a href="{% url 'review_create' %}">Create review</a> 

{% endblock %}

sport_catalog/templates/sport_catalog/sportsmen_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Sportsmen List</h1>

    {% if sportuser_list %}
    <ul>

      {% for sportsman in sportuser_list %}
      <li>
        <a href="{{ sportsman.get_absolute_url }}">{{ sportsman.first_name }} {{ sportsman.last_name }}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no sportsmen.</p>
    {% endif %}
{% endblock %}

sport_catalog/templates/sport_catalog/sportuser_detail.html
{% extends "base_generic.html" %}
{% block content %}
  
  <h1>User: {{ sportuser.user.get_username }}</h1>

  <p><strong>first_name:</strong> <a href="">{{ sportuser.first_name }}</a></p> 
  <p><strong>last_name:</strong> <a href="">{{ sportuser.last_name }}</a></p> 
  <p><strong>Sportsman;</strong> <a href="">{{ sportuser.isSportsMen }}</a></p> 
  <p><strong>Manager:</strong> <a href="">{{ sportuser.isManager}}</a></p> 


{% endblock %}